// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateReservedUserForm {
    "Name": string;
    "Account": string;
    "Password": string;

    /** Creates a new CreateReservedUserForm instance. */
    constructor($$source: Partial<CreateReservedUserForm> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Account" in $$source)) {
            this["Account"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateReservedUserForm instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateReservedUserForm {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateReservedUserForm($$parsedSource as Partial<CreateReservedUserForm>);
    }
}

export class ReservedUserInfo {
    "Name": string;

    /** Creates a new ReservedUserInfo instance. */
    constructor($$source: Partial<ReservedUserInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReservedUserInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ReservedUserInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReservedUserInfo($$parsedSource as Partial<ReservedUserInfo>);
    }
}
