// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function GetOptions():Promise<Array<entity.Option>>;

export function SaveOption(arg1:entity.Option):Promise<boolean>;
