// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as views$0 from "../views/models.js";

export function CreateReservedUser(form: views$0.CreateReservedUserForm): $CancellablePromise<views$0.ReservedUserInfo> {
    return $Call.ByID(532023624, form).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetReservedUserInfo(): $CancellablePromise<views$0.ReservedUserInfo> {
    return $Call.ByID(638319042).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = views$0.ReservedUserInfo.createFrom;
