// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOptions() {
  return window['go']['service']['Option']['GetOptions']();
}

export function SaveOption(arg1) {
  return window['go']['service']['Option']['SaveOption'](arg1);
}
